# Generated by Django 5.1.1 on 2024-09-27 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChapterChoice_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Book_brand',
            new_name='Book_author',
        ),
    ]
