# Generated by Django 5.1.1 on 2024-09-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChapterChoice_app', '0002_rename_book_brand_book_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reg',
            name='u_mobile',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
