# Generated by Django 5.1.1 on 2024-09-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChapterChoice_app', '0003_alter_user_reg_u_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reg',
            name='u_mobile',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
