# Generated by Django 5.1.1 on 2024-09-27 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChapterChoice_app', '0004_alter_user_reg_u_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Book_image2',
        ),
        migrations.RemoveField(
            model_name='book',
            name='Book_image3',
        ),
        migrations.RemoveField(
            model_name='book',
            name='Book_image4',
        ),
    ]
